# Análise do consumo e preço de combustíveis (Etanol x Gasolina)

Base de dados ´.CSV´ do app [Drivvo](https://www.drivvo.com/pt/).

## Índice

- [Extração dos dados](#extracao)
- [Tratamento de dados](#tratamento)
- [Análise](#analise)
- [Conclusão](#conclusao)

## Extração dos dados <a class = "anchor" id = "extracao" ></a>

In [146]:
import pandas as pd

# importar dados
print([1])
tabela = pd.read_csv(r'C:\Users\elias\Downloads\20210508_135821_DRIVVO.csv', encoding = 'latin1')
display(tabela)

# outras formas de verificar informações do conteúdo do arquivo
print([2])
display(tabela.info)

print('\n',[3])
print(tabela.info())

print('\n',[4])
display(tabela.columns)

'''
depois pesquisar como fazer para buscar o arquivo independente da data, ou seja, 
sempre buscar pelo último "_DRIVVO.csv" e não pelo nome completo do arquivo;
'''

[1]

                                                                                                                                                                                                                                                                                                                    #Abastecimento
Odômetro (km)       Data                Combustível      Preço / L      Valor total    Volume                Completou o tanque Segundo combustível Preço / L        Valor total Volume     Completou o tanque 2 Terceiro combustível Preço / L Valor total Volume Completou o tanque 3 Posto de combustível Motivo     Observação
83442               2021-05-07 15:09:31 Etanol           3.899          181.97         46.671                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
83200               2021-04-20 18:10:30 Etanol           3.599          150.91         41.931                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
82954               2021-04-07 17:18:51 Etanol           3.499          158.01         45.159                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
82701               2021-03-15 10:15:56 Etanol           3.979          183.35         46.079                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
...                                                                                                                                                                                                                                                                                                                            ...
74153               2020-01-07 18:51:38 104.87           Licenciamento  NaN            NaN                   NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
72700               2019-11-14 18:08:41 1656.4           Seguro         NaN            Pago em 10x sem juros NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
#Percurso           NaN                 NaN              NaN            NaN            NaN                   NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
Data inicial        Data final          Odômetro inicial Odômetro final Distância (km) Valor km              Total              Origem              Destino          Motivo      Observação NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
2020-09-26 17:30:30 2020-09-29 19:00:55 79000            79796          796            0.1                   79.600             Casa                Caraguatatuba-SP NaN         Viagem     NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN

[74 rows x 1 columns]

[2]

<bound method DataFrame.info of                                                                                                                                                                                                                                                                                                                     #Abastecimento
Odômetro (km)       Data                Combustível      Preço / L      Valor total    Volume                Completou o tanque Segundo combustível Preço / L        Valor total Volume     Completou o tanque 2 Terceiro combustível Preço / L Valor total Volume Completou o tanque 3 Posto de combustível Motivo     Observação
83442               2021-05-07 15:09:31 Etanol           3.899          181.97         46.671                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
83200               2021-04-20 18:10:30 Etanol           3.599          150.91         41.931                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
82954               2021-04-07 17:18:51 Etanol           3.499          158.01         45.159                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
82701               2021-03-15 10:15:56 Etanol           3.979          183.35         46.079                Sim                NaN                 0                0           0          Não                  NaN                  0         0           0      Não                  Del Rey (Rotatória)  NaN               NaN
...                                                                                                                                                                                                                                                                                                                            ...
74153               2020-01-07 18:51:38 104.87           Licenciamento  NaN            NaN                   NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
72700               2019-11-14 18:08:41 1656.4           Seguro         NaN            Pago em 10x sem juros NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
#Percurso           NaN                 NaN              NaN            NaN            NaN                   NaN                NaN                 NaN              NaN         NaN        NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
Data inicial        Data final          Odômetro inicial Odômetro final Distância (km) Valor km              Total              Origem              Destino          Motivo      Observação NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN
2020-09-26 17:30:30 2020-09-29 19:00:55 79000            79796          796            0.1                   79.600             Casa                Caraguatatuba-SP NaN         Viagem     NaN                  NaN                  NaN       NaN         NaN    NaN                  NaN                  NaN               NaN

[74 rows x 1 columns]>

 [3]
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74 entries, ('Odômetro (km)', 'Data', 'Combustível', 'Preço / L', 'Valor total', 'Volume', 'Completou o tanque', 'Segundo combustível', 'Preço / L', 'Valor total', 'Volume', 'Completou o tanque 2', 'Terceiro combustível', 'Preço / L', 'Valor total', 'Volume', 'Completou o tanque 3', 'Posto de combustível', 'Motivo') to ('2020-09-26 17:30:30', '2020-09-29 19:00:55', '79000', '79796', '796', '0.1', '79.600', 'Casa', 'Caraguatatuba-SP', nan, 'Viagem', nan, nan, nan, nan, nan, nan, nan, nan)
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   #Abastecimento  11 non-null     object
dtypes: object(1)
memory usage: 17.5+ KB
None

 [4]

Index(['#Abastecimento'], dtype='object')

'\ndepois pesquisar como fazer para buscar o arquivo independente da data, ou seja, \nsempre buscar pelo último "_DRIVVO.csv" e não pelo nome completo do arquivo;\n'

### Considerações

- O arquivo apresentou erro na primeira importação dos dados e pelo o que eu entendi foi um erro de decodificação. Acrescentei um parâmetro dentro do `pd.read_csv`, o **`encoding = 'latin1'`**;  
- Há também diversos valores nulos (NaN) que deverão ser tratados antes da análise e a remoção de algumas colunas como 'Segundo combustível' e outras mais por não conterem valores para a análise;  
- Rever o `print(tabela.info())` após tratamento dos dados, pois apresentou comportamento estranho, mostrou somente 1 coluna total;  
- Não ouve entendimento para o print do `""" """`, que no Python é um comentário quando se tem várias linhas e utilizado em substituição do `#`.

## Tratamento de dados <a class = "anchor" id = "tratamento" ></a>

In [157]:
# remoção das colunas desnecessárias;
print('[1]')
tabela = pd.read_csv(r'C:\Users\elias\Downloads\20210508_135821_DRIVVO.csv', encoding = 'latin1', skiprows = 1)
print(tabela.info(),'\n')

print('[2]')
tabela = tabela.drop(['Data', 'Completou o tanque', 'Segundo combustível', 'Preço / L.1', 'Valor total.1', 
                      'Volume.1', 'Completou o tanque 2', 'Terceiro combustível', 'Preço / L.2', 'Valor total.2', 'Volume.2', 
                      'Completou o tanque 3', 'Posto de combustível', 'Motivo', 'Observação'], axis = 1)
print(tabela.info())
display(tabela)


# selecionar apenas linhas com os combustíveis;
print('[3]')
# tabela[tabela['Combustível'] == 'Etanol']    #-------> Só funciona para um argumento;
tabela[tabela['Combustível'].isin(['Etanol', 'Gas. Aditivada', 'Gas. Comum'])]
display(tabela)

'''
para uma lista de argumentos:
    .isin(["lista de argumentos"])
    Lê-se: na tabela, na coluna Combustível da tabela, filtrar "Etanol", "Gas. Aditivada" e "Gas. Comum"
    
ou "string contains":
    df[df['col3'].str.contains('py|dat|\+')]    
    Lê-se: no dataframe, na col3 do dataframe, filtrar strings que contém: "py", "dat", "+"
'''


# remoção de valores nulos por coluna;

[1]
[2]
[3]

,Odômetro (km),Combustível,Preço / L,Valor total,Volume
0,83442,Etanol,3.899,181.97,46.671
1,83200,Etanol,3.599,150.91,41.931
2,82954,Etanol,3.499,158.01,45.159
3,82701,Etanol,3.979,183.35,46.079
4,82399,Gas. Aditivada,4.549,192.38,42.291
...,...,...,...,...,...
68,74153,104.87,Licenciamento,NaN,NaN
69,72700,1656.4,Seguro,NaN,Pago em 10x sem juros
70,#Percurso,NaN,NaN,NaN,NaN
71,Data inicial,Odômetro inicial,Odômetro final,Distância (km),Valor km
72,2020-09-26 17:30:30,79000,79796,796,0.1

'\npara uma lista de argumentos:\n    .isin(["lista de argumentos"])\n    Lê-se: na tabela, na coluna Combustível da tabela, filtrar "Etanol", "Gas. Aditivada" e "Gas. Comum"\n    \nou "string contains":\n    df[df[\'col3\'].str.contains(\'py|dat|\\+\')]    \n    Lê-se: no dataframe, na col3 do dataframe, filtrar strings que contém: "py", "dat", "+"\n'

### Considerações

- Foi constatado que as colunas com os dados a serem considerados na análise são submenus da coluna "#Abastecimento" e por isso o código `display(tabela.columns)` na extração dos dados apresentou um comportamento extranho:
- Corrigido com o parâmetro `skiprowns = 1` (pula a primeira linha na extração dos dados) do `pd.read_csv`. O padrão é `skiprows=None`;
- Para remover várias colunas, tem que colocar `.drop(['colunas1', 'coluna2'], axis = 1)`;
- Foi feita a seleção somente dos combustíveis e

## Análise <a class = "anchor" id = "analise" ></a>

In [ ]:
codigo

### Considerações

texto

## Conclusão <a class = "anchor" id = "conclusao" ></a>

texto